### ISSUE TITLE
The game shows only a black screen when launched

### ISSUE THREAD

**Issue by Marcus-Arcadius** [hmlendea/gfn-electron#100]
### Describe the bug

My dashboard shows up perfect but when I start any game, it's just a black screen, and all I hear is the audio....

### To Reproduce

Launch any game

### Operatingsystem

solus

### Desktop Environment

budgie

### Installation method

github

### Version

1.1.12

**Comment by hmlendea** [comment]
- Does this happen with other installation methods? (flatpak, AppImage, etc)
 - Can you at least see the loading screen? _(the one in the image below)_
 
![image](https://user-images.githubusercontent.com/10261133/151818512-e60f8686-977e-47ae-aac6-d7a8747d4e40.png)
