### ISSUE TITLE
[BUG] iHD_drv_video.so init failed 

### ISSUE THREAD

**Issue by utherbone** [hmlendea/gfn-electron#102]
### Describe the bug

iHD_drv_video.so init failed 

### To Reproduce

Extract and start in terminal emulator

### Screenshots

![2022-02-05_16-55](https://user-images.githubusercontent.com/13210391/152658762-fda1713a-b2cb-4fbd-8acf-cc7034883d3f.png)
![image](https://user-images.githubusercontent.com/13210391/152659204-643c06fa-44ca-4f2e-8bf9-731b651f44d7.png)

### Operatingsystem

Zorin OS Lite

### Desktop Environment

XFCE

### Installation method

Donqload ".zip" Run with coammand line

### Version

1.1.12

### Additional context

GPU
`glxinfo | grep Mesa
client glx vendor string: Mesa Project and SGI
    Device: Mesa DRI Intel(R) HD Graphics (ILK) (0x42)
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics (ILK)
OpenGL version string: 2.1 Mesa 21.3.5 - kisak-mesa PPA
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 21.3.5 - kisak-mesa PPA
`

**Comment by hmlendea** [comment]
Hi,

Is there a VA driver installed and up-to-date on your system?

Can you send the output of `lspci | grep VGA` ?

Can you also install libva-utils (not sure how the package is called on Ubuntu-based systems) and send the output of `vainfo`?

You could also try using the flatpak/version and see if it works better for you.

**Comment by utherbone** [comment]
```
lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller (rev 18)

vainfo
libva info: VA-API version 1.12.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.12 (libva 2.6.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Ironlake Desktop - 2.4.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```
I try flastpack soon

**Comment by hmlendea** [comment]
`libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed`
there seems to be a problem with VA on your system.

Is the `libva` package installed?

**Comment by utherbone** [comment]
Are these packages available for my distro https://launchpad.net/ubuntu/focal/+search?text=libva
When I install the "mesa" Driver it installs "libva2"
A print from the "dri" directory where you have the 'lib" with error
![image](https://user-images.githubusercontent.com/13210391/153742562-9e3c03cc-76f5-4da0-b376-5f202edd7c92.png)

**Comment by utherbone** [comment]
Hello, my onboard video card that is not supported by the desktop driver, not in its magnitude so the error when loading the library, I tested the memso ssd with Linux Zorin installed on a ryzen atlhon 200ge and ran well.

**Comment by utherbone** [comment]
Taking advantage of the post, it would be nice to have a shortcut to activate the window in full scream, when minimiso it does not return to get full scream.

**Comment by hmlendea** [comment]
> Taking advantage of the post, it would be nice to have a shortcut to activate the window in full scream, when minimiso it does not return to get full scream.

The full-screen toggle shortcut is `Super + F`

**Comment by UwUnyaa** [comment]
Have you tried setting the `LIBVA_DRIVER_NAME`? In your case, the value of `i965` should do the trick. Chromium can be a bit flaky when it comes to picking the right driver without any hints.

ArchWiki has the relevant documentation about configuring this environment variable: https://wiki.archlinux.org/title/Hardware_video_acceleration#Configuring_VA-API

**Comment by hmlendea** [comment]
There's been some changes recently. Does this issue still occur on the latest version?
