### ISSUE TITLE
[Feature reqest] increase bitrate beyond 50mbps

### ISSUE THREAD

**Issue by sigboe** [hmlendea/gfn-electron#103]
Hi,
In the windows and mac native app, the settings are written to files in clear text. So a Windows or Mac user can just change the value to any number. I've read people online have changed it to ridiculously high numbers and noted that they get over 80mbps, compared to the 50mbps which is the highest number allowed to set in the UI. I guess the real limit might be different in each data center.

My biggest gripe thus far with GFN is that it really looks like I am watching a youtube video, I know that going from 50 to 80 mbps won't remove this look completely, but it is a significant improvement, lessening the effect of this. 

Do you think that altering the max value of the slider using a javascript file added to the electron app, like people add userscripts to their browser?

**Comment by andrewgdunn** [comment]
Is this something that is limited upstream or is a limit locally?

**Comment by sigboe** [comment]
> Is this something that is limited upstream or is a limit locally?

Hello @andrewgdunn This is ultimately limited locally,
there is a limit on the server side, but it is not designed in, if you set the bitrate to something really high, and your network connection can deliver, then users reports that it fluxuates around 80mpbs

**Comment by xor-128** [comment]
Geforce NOW already supports 75mbps on Web.

**Comment by sigboe** [comment]
@xor-128 Yes sorry for forgetting about this issue and not locking it, 75mbps is decent enough
