### ISSUE TITLE
Cannot change keyboard layout - Idea

### ISSUE THREAD

**Issue by SoftwareRat** [hmlendea/gfn-electron#104]
You could add an argument like "--useragent-windows" which runs GFN with Windows useragent, since GFN doesn't show keyboard layout settings with Linux useragent for some reason.

**Comment by hmlendea** [comment]
Thanks.

I will likely add this, as well as a flag for spoofing ChromeOS.

This would fix #76

**Comment by SoftwareRat** [comment]
Any new news?

**Comment by hmlendea** [comment]
I was trying to find a way to do it automatically without the need to use the command line, but didn't manage to find a reliable solution.

I will add the argument. If I find something better in the future, I'll change it then. But at least there's something in the meantime, even though it's not user-friendly.

**Comment by hmlendea** [comment]
Ok so I tried doing this today, but I reached a roadblock...
It doesn't seem like setting the useragent to either ChromeOS or Windows allows me to change the keyboard layout.

I've also tried it in the browser (Chromium) and it the same over there also.

**Comment by SoftwareRat** [comment]
> Ok so I tried doing this today, but I reached a roadblock... It doesn't seem like setting the useragent to either ChromeOS or Windows allows me to change the keyboard layout.
> 
> I've also tried it in the browser (Chromium) and it the same over there also.

I managed to change to `Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.7113.93 Safari/537.36` and voila, I got Keyboard layout settings.

Worked after launching Chromium with `--disable-features=UserAgentClientHint` argument

**Comment by hmlendea** [comment]
Hmmm I tried this but it doesn't work for me. I also tried completely wiping browsing data but it didn't help.
What user agent switcher extension did you use? I tried two of them with no luck.

**Comment by SoftwareRat** [comment]
https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg

I followed the steps from https://wiki.archlinux.org/title/GeForce_Now#Non-qwerty_keyboard_layout

**Comment by oktayacikalin** [comment]
Hmm.. I've installed 1.4.0 via flathub on elementary OS. The spoofing argument is either not being given to the executable, or it just doesn't work. Anything I can do?

**Comment by hmlendea** [comment]
Let me know if anyone still experiences issues with this in the latest version please.

**Comment by SoftwareRat** [comment]
I just used an workaround for this:

1. Install some Chromium browser
2. Follow these steps: https://wiki.archlinux.org/title/GeForce_Now#Non-qwerty_keyboard_layout
3. Open `chrome://version` and open the path on "Profile Path"
4. There should be a folder called `IndexedDB`
5. Open path of geforcenow-electron (On Flathub, it should be `~/.var/app/io.github.hmlendea.geforcenow-electron/config/GeForce NOW/`
6. Copy the IndexedDB folder from Step 4 to geforcenow-electron path

Now the keyboard layout should be changed to your preference

**Comment by lgromb** [comment]
@hmlendea this is still a problem on Ubuntu 22.04 to this day.

**Comment by krptg0** [comment]
@hmlendea This is still an ongoing issue on Ubuntu 22.04, nor chromeos or windows UA allow me to change keyboard layout.

**Comment by chriskaya** [comment]
Hi there
This could be fixed by #176

**Comment by hmlendea** [comment]
This should be fixed by some of the merged PRs. Please feel free to comment and/or re-open this issue if it still persists.
