### ISSUE TITLE
[BUG] Cannot Login With Partner Account

### ISSUE THREAD

**Issue by SerhatGulasti** [hmlendea/gfn-electron#126]
### Describe the bug

I'm trying to login with Game+ (GFN's Turkey alliance) account but when I try to login I just get a gray screen

### To Reproduce

1. Try to login
2. Login page redirected me to Game+'s login page
3. Try to login to my account
4. Getting a gray screen and I cant see any change in main screen

### Screenshots

![Screenshot_20220507_015833](https://user-images.githubusercontent.com/13099988/167226021-d841ba51-a873-46d7-a7bd-7d2e82f12b99.png)

### Operatingsystem

Arch Linux

### Desktop Environment

KDE

### Installation method

flatpak

### Version

1.5.1

**Comment by kundius** [comment]
the same with aur package

**Comment by rivasue** [comment]
I can confirm that this issue is ongoing. After countless tries, I was able to see that i logged in to the website. (It only occured one time.)
Manjaro with KDE
Dowloaded via aur
1.5.1

**Comment by hmlendea** [comment]
Related to #125 

Should be fixed in [v1.5.2](https://github.com/hmlendea/gfn-electron/releases/tag/v1.5.2) (by #127)

**Comment by SerhatGulasti** [comment]
Yeah fixed. Thanks for your help.
