### ISSUE TITLE
[BUG] If I wrote first character in Steam password, I can't write anything more

### ISSUE THREAD

**Issue by SoongVilda** [hmlendea/gfn-electron#132]
### Describe the bug

**Following behavior observed on Wayland:**
I can't write my password, if I hit any button it will write first character and bottom KDE bar appear (Something like exiting fullscreen) and I can't write anything more. I can only close geforce now.

**If i switched back to X11:**
I can write password, but bottom KDE bar appearing, existing fullscreen if I played anything. 

I used gfn-electron some time ago without issues, but now, I can't simply write password.

### To Reproduce

1. Open gfn-electron
2. Chose any game
3. Start writing password into the Steam.

### Screenshots

![Screenshot_20220509_180706](https://user-images.githubusercontent.com/61845673/167496009-108510d1-c81a-4ebc-9ab5-5b0c068de714.png)

### Operatingsystem

Arch Linux

### Desktop Environment

KDE Plasma

### Installation method

AUR

### Version

1.6.0-1

**Comment by hmlendea** [comment]
Please let me know if this is still an issue in the latest version (1.7.0)

**Comment by SoongVilda** [comment]
Issues persistent, I reinstalled my Arch and installed gfn-electron. Nothing changed.

**Comment by extremegrief1** [comment]
I have the same bug since a few versions ago, hopefully it is client-side and can be fixed.

**Comment by hmlendea** [comment]
Could you also give the flatpak version a try and see if it works?

**Comment by SoongVilda** [comment]
I tried flatpak.
X11 - no issue.
Wayland - issue as I described. It worked in the past, but for now it's broken.

**Comment by SoongVilda** [comment]
I can share logs if you tell me how to capture them or try to set remote connection to my second machine with Intel GPU and Nvidia GPU where Wayland works without issue.

**Comment by SoftwareRat** [comment]
Is there really no fix yet?

**Comment by hmlendea** [comment]
This was fixed in already-merged PRs. Please feel free to comment and/or re-open this issue if it still persists for you.
