### ISSUE TITLE
[REQUEST] Add the ability to launch sessions from command line

### ISSUE THREAD

**Issue by extremegrief1** [hmlendea/gfn-electron#140]
Hello, is it possible to add something like this "geforcenow-electron cmsid=x" or "geforcenow-electron sessionid=x" which launches the session automatically? Windows native version has this option "GeForceNOWStreamer.exe --url-route="#?cmsId='x'&launchSource=External"

**Comment by xor-128** [comment]
Do you mean something like this?

https://youtu.be/oCPqxtUgrNU

**Comment by xor-128** [comment]
#150

**Comment by hmlendea** [comment]
Closing as #150 was merged
