### ISSUE TITLE
[BUG] <ESC> not working anywhere else but geforce-now

### ISSUE THREAD

**Issue by Icy-Thought** [hmlendea/gfn-electron#153]
### Describe the bug

Not only does it lose focus when pressed inside geforce-now (#137), but it also makes it impossible to press <ESC> outside of geforce now.

One example that I have been very bothered by is the inabliltiy to `<ESC>` inside neovim (or any other terminal-app). Because of this issue I am unable to cancel any form of neovim command-related operation unless I either terminate the terminal-tab `||` that I erase the whole operation and hit enter on an empty `:` just to mimick an `<ESC>`.

### To Reproduce

1. Launch `Gefroce Now`
2. Launch neovim in terminal (`nvim`)
3. `:` + input whatever operation you wish to execute. 
    Example: `echo "hello, world!"`
4. Try to cancel operation by hitting `<ESC>`

### Operating System

NixOS

### Desktop Environment

XMonad

### Display Server

X11

### Installation method

packaged the appimage version

### Version

1.7.0

### Is this a fresh install of the app or an update from a past version?

Update from 1.6.0

### Did this issue appear right away upon installation/updating, or spontaneously?

Yes, right after the installation of the latest version

**Comment by Ishidres** [comment]
Same issue.

**Comment by Icy-Thought** [comment]
Also, the double-click focus is not guaranteed. Oftentimes I find myself spamming right-click for the mouse to regain focus, which is in my opinion very frustrating..

**Comment by Icy-Thought** [comment]
> use Shift + Esc

That solution appears to not be working. It's as if the <kbd>Esc</kbd> key is not even recognized when used alongside <kbd>Shift</kbd>.

**Comment by william-p** [comment]
Just a quick fix on https://github.com/hmlendea/gfn-electron/pull/186

I'm not sure if it's okay all the time, this fix need more tests ...

**Comment by hmlendea** [comment]
Closing.

In case this issue still affects anyone, please discuss it in #137
