### ISSUE TITLE
deb for version 1.8.0 

### ISSUE THREAD

**Issue by crchmatefis** [hmlendea/gfn-electron#158]
Can you upload the .deb package of version 1.8.0 please, since only when I install using the .deb does the gamepad recognize me.

I just tried installing by flatpak and by snap and with neither of them does the gamepad recognize me. I won't be able to use the new versions of gfn-electron anymore :(

**Comment by hmlendea** [comment]
Hello.

The problem with deb (and other distro-specific packages) is that I cannot test them. There were many issues reported for it and I was unable to address them, and kept piling up.
This is why I decided to drop support for the legacy packages and only keep the new distro-agnostic ones. Flatpak (main), snap and AppImage should all work on Debian for example.

In regards to the gamepad issue. For flatpak, if it doesn't work, can you try these steps? https://github.com/hmlendea/gfn-electron/wiki/Troubleshooting
And, does it also not work at all in snap / AppImage?

**Comment by crchmatefis** [comment]
1) Can you try these steps? https://github.com/hmlendea/gfn-electron/wiki/Troubleshooting

Answer: I tried the steps, but none of them detected my gamepad.

2) And doesn't it work on snap/AppImage either?

answer: snap/AppImage doesn't detect my gamepad either.

Data: I use ubuntu 22.04(X11)
