### ISSUE TITLE
[BUG] [Steam Deck] problem starting app from Steam Library

### ISSUE THREAD

**Issue by kachaj** [hmlendea/gfn-electron#166]
### Describe the bug

Flatpak version of the app starts but only displays error that there was a problem connecting to GeforceNow.
The screenshot shows differences between flatpak version (left) and binary version (right).
I would go with binary version but when I try to run it from Steam Library (either Game Mode or Desktop Mode) the app draws window for a split second and then it crashes.
Binaries work only in Desktop Mode.

### To Reproduce

1. Install flatpak version, add permissions for udev:ro, run app, error connecting to GeforceNOW.
2. Download binaries from releases, unpack, run binary - works.
3. Add binaries to Steram Library, run app from Library - crash. 

### Screenshots

![image](https://user-images.githubusercontent.com/6377140/187418556-7ca8323f-2a4d-497a-b571-46e8886e4015.png)

### Version

1.9.0, 1.8.0(binary)

### Is this a fresh install of the app or an update from a past version?

fresh and update

### Did this issue appear right away upon installation/updating, or spontaneously?

I believe it started after updating but can't pinpoint if it was app update or SteamDeckOS update.

**Comment by hmlendea** [comment]
I should soon receive my Steam Deck (finally) and I'll investigate this issue when I'll have some time. Right now I'm quite full with IRL things.

**Comment by hmlendea** [comment]
Is this issue still affecting the latest supported versions?
