### ISSUE TITLE
Missing back-to-gfn functionality for external links

### ISSUE THREAD

**Issue by dsv9** [hmlendea/gfn-electron#169]
### Describe the bug

When a user is redirected to an external link inside the GFN app, it's impossible to return to the GFN Now platform due to a lack of a back-to-gfn functionality, any Back buttons or a dedicated and permanent UI menu of the GFN platform for Home, Library and any other elements which are part of the GFN main menu.

### To Reproduce

1. Select a game that is not in your library.
2. Select a provider, ex: Steam
3. Click on GET in order be redirected to the game's page for that specific provider.
4. Attempt to go back to GFN.

### Operating System

Ubuntu 22

### Desktop Environment

Gnome 42, Regolit2

### Display Server

X11

### Installation method

Snap

### Version

1.10.0

### Is this a fresh install of the app or an update from a past version?

Fresh

### Did this issue appear right away upon installation/updating, or spontaneously?

Yes, right after

**Comment by hmlendea** [comment]
Closed as this is an issue related to the `snap` version which was dropped in #191.
