### ISSUE TITLE
[Request] Locale selector (SteamDeck?)

### ISSUE THREAD

**Issue by nanotechnician** [hmlendea/gfn-electron#170]
Hello, I want to use this on the Steam Deck but something inside the system itself is preventing me to choose another Locale to launch games in my language (the same is happening systemwide with Chrome, Edge, etc... I have to force my language (in this case Spain spanish, es_ES, via third party extension Locale changer) 

Is there a way I can successfully start with a preferred Locale? arguments like --lang=es_ES dont work 100% because gfn detects It as es_MX i.e. and games turn out mixed english with subtitles.

Solved It inside Chrome with a third party extension that forces webpages in es_ES and games work in spanish as in the Windows Desktop GFN app.

Just curious If It can be done so I can placebo myself using this instead of a Chrome tab, thank you for your work.

**Comment by chriskaya** [comment]
Hi there!
This could be fixed by #176 
Is there a way you can try by building my fork? IDK if that's possible on Steam Deck though

**Comment by chriskaya** [comment]
Fixed by #183

**Comment by hmlendea** [comment]
Closing, as this should have been fixed as part of #183. If it still persists, feel free to comment and/or reopen this issue.

**Comment by Movion** [comment]
That PR https://github.com/hmlendea/gfn-electron/pull/183 got closed without a merge as the participant stopped 
https://github.com/hmlendea/gfn-electron/pull/183#issuecomment-1914258786

The issue should be opened again.
