### ISSUE TITLE
[BUG] I can't find Genshin Impact

### ISSUE THREAD

**Issue by TobyG74** [hmlendea/gfn-electron#171]
I can't find Genshin Impact in this version, but for other version like windows and android found. Is it true that this version doesn't support this game??

**Comment by Madeleaan** [comment]
Nvidia for some reason restricted the game to only work in the windows app (I also heard people got around it by changing their user agent to a windows one). If you search it up, you can find many reddit posts about people having the same issue.

**Comment by bergamin** [comment]
I tried the user agent trick and somehow the website still detects I'm on Linux. It works for whatismybrowser.com for example, but it doesn't for Geforce Now (it stores the data in the local storage and even cleaning it up and changing the user agent, it still populates as Linux)

**Comment by CheesyChocolate** [comment]
i tried changing user agent in source, but no luck there. [https://github.com/hmlendea/gfn-electron/compare/master...CheesyChocolate:gfn-electron:patch-1?expand=1](url) .
the same user agent works fine in chrome.
maybe i build the npm packages wrong

**Comment by Sverik** [comment]
Interestingly enough, my Linux native Chrome can get Genshin Impact running if switching user agent to this silly thing with the user agent switcher extension:

    Mozilla/4.0 (compatible; MSIE 7.0; AOL 9.5; AOLBuild 4337.80; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)

For some reason, using `Network conditions` to spoof user agent in GFE Electron does not have the same effect.

**Comment by bergamin** [comment]
> Interestingly enough, my Linux native Chrome can get Genshin Impact running if switching user agent to this silly thing with the user agent switcher extension:
> 
> ```
> Mozilla/4.0 (compatible; MSIE 7.0; AOL 9.5; AOLBuild 4337.80; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)
> ```
> 
> For some reason, using `Network conditions` to spoof user agent in GFE Electron does not have the same effect.

How do you do set it up? It's still not loading it for me even when using the extension. This is what I get from whatismybrowser.com

![image](https://user-images.githubusercontent.com/14339291/211157502-77bdea16-5868-445b-90f9-6790512c3647.png)

**Comment by Sverik** [comment]
[useragent-switcher-preferences.json.txt](https://github.com/hmlendea/gfn-electron/files/10371722/useragent-switcher-preferences.json.txt)
Attached is export from my User Agent Switcher configuration. Note that there's a list of all the domains for which spoofing is active. Maybe not all are needed, but I wasn't able to figure out which was the most important domain. So I just added all that I saw in dev tools Network tab, that seemed to have some relation to nvidia and geforce now.

**Comment by bergamin** [comment]
It seems to work, but it took me some time to find the correct extension. I was trying to import into the wrong ones

This is the one:
https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg

**Comment by Sverik** [comment]
Indeed, yes!

Kontakt Guilherme Taffarel Bergamin ***@***.***>) kirjutas
kuupäeval T, 10. jaanuar 2023 kell 04:52:

**Comment by hmlendea** [comment]
Closing, as this should have been fixed as part of #184. If it still persists, feel free to comment and/or reopen this issue.
