### ISSUE TITLE
[BUG]Esc key catched by both local PC and geforce now game

### ISSUE THREAD

**Issue by Madame-Louise** [hmlendea/gfn-electron#194]
### Describe the bug

When in a game, pressing the escape key will make the geforce now app leave full screen mode wich completely breaks immersion (though the game does catch the esc input too). I tested this on Wayland and X11 and the problem is here on both these display server.

### To Reproduce

1. Fresh install the snap version of the app
2. Launch a game 
3. Press the esc key

### Operating System

Ubuntu 23.04

### Desktop Environment

GNOME 44.2

### Display Server

X11 / Wayland

### Installation method

snap

### Version

latest (1.10.0)

### Is this a fresh install of the app or an update from a past version?

fresh install

### Did this issue appear right away upon installation/updating, or spontaneously?

The issue appeared right after install.

**Comment by Taurolyon** [comment]
Same issue on Debian 12 with manual install. The escape key disconnects the mouse from the game, and requires the user to click/right-click to reconnect the mouse to the game.

**Comment by Sivarion** [comment]
The same on Manjaro - hitting ESC leaves full screen and disconnects the mouse, while GFN shows "You need to be full screen, do you want to leave the game?" prompt. Really annoying, as ESC is widely used control for most games.

**Comment by FLAGEL** [comment]
I am unsure if related, but pressing Esc while gfn-electron is unfocused (e.g. browsing with a browser in a different workspace) will register as pressing Esc in gfn-electron. 

**Setup**
[1] io.github.hmlendea.geforcenow-electron 2.0.1
[2] Linux host 6.6.8-arch1-1 https://github.com/flightlessmango/MangoHud/pull/1 SMP PREEMPT_DYNAMIC Thu, 21 Dec 2023 19:01:01 +0000 x86_64 GNU/Linux
[3] xfce4 4.18

**Comment by hmlendea** [comment]
Closing.

In case this issue still affects anyone, please discuss it in #137
