### ISSUE TITLE
[Feature] Configuration file

### ISSUE THREAD

**Issue by Mageti** [hmlendea/gfn-electron#197]
### Describe the bug

Hello,
I think it could be great to be able to have a configuration file, and put in it some options, like spoofing the user-agent.
I have a linux computer and certain games are not available on linux, only on windows. When I play, I use the command line and use the `--spoof-windows --disable-rpc` arguments, but my children do not use the CLI, the use the icon in my GDM.
If a config file was available, I could put that in it and everything would be smooth for the whole family.

I would gladly help you, but I do not know JS, sorry.

### To Reproduce

Well, not really a bug, more of a feature request

### Operating System

ArchLinux

### Desktop Environment

GNOME 44

### Display Server

wayland

### Installation method

zip

### Version

1.12

### Is this a fresh install of the app or an update from a past version?

not applicable :-)

### Did this issue appear right away upon installation/updating, or spontaneously?

not aplicable :-)

**Comment by hmlendea** [comment]
Closing this as OS spoofing is getting removed (See #209).
