### ISSUE TITLE
[BUG] [Steam Deck]

### ISSUE THREAD

**Issue by seavers11** [hmlendea/gfn-electron#204]
### Describe the bug

Gfn electron doesnt start in gaming mode herein?!

### To Reproduce

1. Install gfn
2. Boot to gamemode
3. Try to run gfn

### Version

Latest

### Is this a fresh install of the app or an update from a past version?

Fresh

### Did this issue appear right away upon installation/updating, or spontaneously?

Always

**Comment by hmlendea** [comment]
Closed due to lack of details and activity.

If you still have issues that need resolving, update this issue with more details and then reopen it; or open a new issue.
