### ISSUE TITLE
[BUG] [Steam Deck] - controller only works in game and no full screen on startup

### ISSUE THREAD

**Issue by ravinsweden** [hmlendea/gfn-electron#214]
### Describe the bug

Im launching the flatpak app from steam big picture (aka SteamOS game mode) as non steam
Game, with all the cmd parameters provided from this forum and when launching the flatpak I can’t navigate the GeForce landing site with the controller sticks or buttons, I’m forced to use the touch screen to navigate, when launching a game the controller works perfectly for the game. How can I enable so that I can navigate with steam controller on the flatpak GeForce landing site? Btw the screen is strangely also not full screen when opening the flatpak, it’s in a smaller squared box, it seems to switch to full screen when exiting a game, can this also be fixed on start-up?

### To Reproduce

Launch electron 2.0 through steam big picture /
SteamOS game mode as non steam game.
Enable controller in steam ui for this game/app.

flatpak --user override --filesystem=/run/udev:ro io.github.hmlendea.geforcenow-electron

### Version

2.0

### Is this a fresh install of the app or an update from a past version?

Fresh install 

### Did this issue appear right away upon installation/updating, or spontaneously?

Yes first time using

**Comment by ravinsweden** [comment]
An update after more testing, if I assign mouse command to a button on the gamepad I can left-click on items on the GeForce landing site and launch games. It seems like the GeForce now electron flatpak doesn’t accept the standard Xbox gamepad layout. The gamepad works great navigating in steam desktop mode or through Google but not when launching within steam game mode, is it possible to adapt the flatpak to support gamepad input like cross/sticks and buttons? Using traditional mouse commands is cumbersome.

**Comment by razaretiwala** [comment]
Did you ever find a fix for this? The instructions in the wiki wouldn't work for me, for some reason.

**Comment by hmlendea** [comment]
GFN Electron uses the official GFN Webapp to work, that being the website not some native app, this is why the controller input is not working.

And in regards to launching game in full screen, we already have an issue open (#196).

Closing this for now as unfixable. Further conversations about the fullscreen issue should be done in #196
