### ISSUE TITLE
HDR support for Steam Deck OLED [Feature] [Steam Deck]

### ISSUE THREAD

**Issue by ddmagnas** [hmlendea/gfn-electron#216]
### Describe the bug

GeForce Now app does not surface HDR settings when launched in Game Mode as a non-Steam app on the Steam Deck OLED.

Would love to be able to stream in HDR!

If it helps, there are other Steam Deck streaming projects (Moonlight and Chiaki4Deck) that have made progress on HDR support:
https://github.com/moonlight-stream/moonlight-qt/issues/1117/
https://github.com/streetpea/chiaki4deck/issues/93

### To Reproduce

1) Open app in Game Mode on a Steam Deck OLED

### Version

2.0.1

### Is this a fresh install of the app or an update from a past version?

Fresh install

### Did this issue appear right away upon installation/updating, or spontaneously?

Right away

**Comment by arshiatn** [comment]
Quick note: 
Chiaki4Deck version 1.5 got released this week and it got HDR. It fully works
Moonlight got some test AppImages and its HDR is working somewhat properly. Only problem it has is Black not being shown as black in HDR and having to pick automatic decoder to enable HDR. (Maybe more problems but people are fixing the problem)

**Comment by HerrTiSo** [comment]
Won't happen anytime soon, as Nvidia restricts the browser variant of GFN from using HDR and resolutions higher than 1200p.

**Comment by hmlendea** [comment]
This is not possible for the reasons stated by @HerrTiSo -> closing.

In addition to this, I own no HDR monitors to be able to test it.
