### ISSUE TITLE
[BUG] [Steam Deck] - No Control Input even after doing the commands in the wiki

### ISSUE THREAD

**Issue by kingblah** [hmlendea/gfn-electron#223]
### Describe the bug

No control input detected when launching in game mode. 
The only way to click anything in the app is with the touch screen itself. None of the steam deck buttons do anything, except the trackpad which moves the mouse cursor (but does not click).
Button layout is set to 'Gamepad With Mouse Trackpad' 

### To Reproduce

Install
Add `--filesystem=/run/udev:ro` to launch arguments
Run `flatpak --user override --filesystem=/run/udev:ro io.github.hmlendea.geforcenow-electron` in terminal
Try to open in game mode

### Version

2.0.1

### Is this a fresh install of the app or an update from a past version?

Fresh install

### Did this issue appear right away upon installation/updating, or spontaneously?

Yes, straight away

### Additional context

Steam deck OS build 20231122.1 / 3.5.7

**Comment by hmlendea** [comment]
I'm closing this for now. Further controller issues should be discussed in #193
