### ISSUE TITLE
[BUG] Termux Support

### ISSUE THREAD

**Issue by IntinteDAO** [hmlendea/gfn-electron#228]
### Describe the bug

Termux is Terminal Emulator and (Linux) Tools for Android. I hope it's possible to port gfn-electron to Termux.

The problem is with Electron IMO, because Termux have their own Electrum with patches, but GFN-Electron tries to build using Linux version of Electron.

### To Reproduce

1) Install Termux and Dependencies
2) Try to build

[log.txt](https://github.com/hmlendea/gfn-electron/files/14194253/log.txt)

Termux Electron: https://github.com/termux-user-repository/tur/tree/master/tur-continuous/electron

### Operating System

Termux

### Desktop Environment

Xfce4

### Display Server

X11

### Installation method

Build

### Version

Master

### Is this a fresh install of the app or an update from a past version?

Fresh

### Did this issue appear right away upon installation/updating, or spontaneously?

Build

**Comment by Llama037** [comment]
Why would you need termux support if gfn has native android support?

**Comment by hmlendea** [comment]
Unfortunately I cannot help with that personally, as I don't have an Android device. :(

Hopefully someone else can contribute.

**Comment by IntinteDAO** [comment]
> Unfortunately I cannot help with that personally, as I don't have an Android device. :(
> 
> Hopefully someone else can contribute.

Is it possible to force using other Electron binary than system one?

**Comment by hmlendea** [comment]
> > Unfortunately I cannot help with that personally, as I don't have an Android device. :(
> > Hopefully someone else can contribute.
> 
> Is it possible to force using other Electron binary than system one?

I really can't say, I wish I could help you but I don't know anything about running Electron apps on Android unfortunately.

I'm closing this for now as it's outside the scope of this app (getting GFN to work on desktop **Linux**)
