### ISSUE TITLE
[BUG] It works but cannot log in

### ISSUE THREAD

**Issue by iamthejames-dev** [hmlendea/gfn-electron#229]
### Describe the bug

I wanted to run the application through my Arm device, the window opened and worked properly, but when I entered my password and account information correctly in the login section, the login section freezes. Then, I tried to give the application permission to access the opengl drivers, but it still did not work.

orangepi@orangepi5plus:~$ flatpak run io.github.hmlendea.geforcenow-electron
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/geforcenow-electron/node_modules/electron/dist/electron --type=zygote
Gtk-Message: 18:44:42.262: Failed to load module "xapp-gtk3-module"
libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip

Thanks

### To Reproduce

Flatpak Downloaded
Flathub Downloaded
Rebooted System
Geforge Now Electron Downloaded
Runned Geforge Now Electron

### Screenshots

![image](https://github.com/hmlendea/gfn-electron/assets/54379020/08e7cf02-4347-42db-9ee3-5b126ed4bf22)

### Operating System

Ubuntu

### Desktop Environment

Gnome

### Display Server

X11

### Installation method

Flatpak

### Version

2.0.1

### Is this a fresh install of the app or an update from a past version?

2.0.1

### Did this issue appear right away upon installation/updating, or spontaneously?

All Downloads

**Comment by hmlendea** [comment]
Closing this in favour of #203
If you still have this issue, please post further comments there.
