### ISSUE TITLE
Desktop launcher for the .deb installer

### ISSUE THREAD

**Issue by hmlendea** [hmlendea/gfn-electron#23]
Currently the `.deb` installer does not provide a `.desktop` launcher for this application.

This is a problem since it breaks the user's experience, as well as that of the desktop environment.

**Comment by squalou** [comment]
you may want to just try this :

```package.json
...
  "build": {
    "linux": {
      "desktop": {
        "Name": "Geforce NOW"
        },
      "target": [
        "zip",
        "AppImage",
        "deb",
        "apk",
        "snap"
      ],
      "category": "Games",
      "artifactName": "${name}_${version}_linux.${ext}"
    },
   ... 
    ```
    
and add a `icon.png` file in `build/icons/`, 
should just work.

**Comment by hmlendea** [comment]
The flatpak version is the only primary version. Removing the `mustfix` tag with `nice-to-have`

**Comment by hmlendea** [comment]
Support for the `deb` version has been dropped in #144 (scheduled for v.1.7.1)
