### ISSUE TITLE
Off Topic: Install Reshade with Shader Depth3D (Stereoscopic 3D)

### ISSUE THREAD

**Issue by VR-Punk** [hmlendea/gfn-electron#240]
Hi,

can i access a terminal or file browser to setup reshade ?

or do you know how to setup reshade shader (Depth3D) for nvidia freestyle ?

greets

Ingo-Arnold

**Comment by hmlendea** [comment]
You mean a terminal on the remote system?

**Comment by VR-Punk** [comment]
yes

**Comment by hmlendea** [comment]
Unfortunately that's not easily possible, as it it completely dependent on Nvidia rather than this application. And, as far as I know, Nvidia doesn't allow it.

Since it's not really realated to this app I'm going to close this issue.
