### ISSUE TITLE
[BUG] This browser or app may not be secure. 

### ISSUE THREAD

**Issue by ghost** [hmlendea/gfn-electron#256]
### Describe the bug

When trying to log in via google account, I am unable to log in into the google account
This browser or app may not be secure. 
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

### To Reproduce

1. Try to login by selecting login with google account

### Screenshots

![Screenshot_20240930_180532](https://github.com/user-attachments/assets/67fdc283-492f-4663-a6af-bc5674270fce)

### Operating System

Manjaro

### Desktop Environment

KDE

### Display Server

x11

### Installation method

AUR

### Version

2.1.2-1

### Is this a fresh install of the app or an update from a past version?

Fresh

### Did this issue appear right away upon installation/updating, or spontaneously?

Right upon

### Additional context

This can be workarounded by Pressing Learn more and logging in google account on the google's support page that was opened in new window.
Please include this workaround in documentation if fixing this bug is not possible.

**Comment by lucascesar918** [comment]
I found a workaround while it doesn't get fixed. Just log in with your e-mail and password (even if you registered with a Google account). If you haven't set up a password for your account, just do it in account settings.

**Comment by hmlendea** [comment]
Cannot be fixed.

Closed as there's already #49.
