### ISSUE TITLE
ESC exits fullscreen

### ISSUE THREAD

**Issue by worldofgeese** [hmlendea/gfn-electron#53]
In the 1.1.1 snap on Ubuntu 21.04, ESC continues to have the undesired effect of exiting fullscreen.

**Comment by fmoerl-real** [comment]
yes, this is annoying. please provide configurability for another key, because of ESC is one of the most important key in a game.

**Comment by hmlendea** [comment]
I was as of yet unable to reproduce this issue
The full-screen toggle is already re-mapped to Super/WinKey+F (since v1.0.7)

Could you double check which version of gfn-electron is installed?

**Comment by mburakov** [comment]
Unfortunately this still reproduces on version 1.1.2.
I am using this AUR package on Archlinux: https://aur.archlinux.org/packages/geforcenow-electron/

**Comment by tobias-oe** [comment]
I can reproduce this on the current version 1.1.3 installed from snap on Ubuntu 20.04 (with Budgie Desktop + XServer)
When I hit ESC in game, the full-screen exits.
But when I use the workaround from #56 to exit and then start full-screen again by hitting Super+F (but I have to hit Super+F twice (double-click like) each time), the ESC key is fixed for that session until i restart the game.
I also installed gfn-electron from sourcecode, but with the same behaviour.

**Comment by nsrosenqvist** [comment]
This is still an issue for me on 1.1.6

**Comment by thomasnaudin** [comment]
Still an issue on 1.1.11.

Fedora 35, Gnome & Wayland
Installed via Flatpak

**Comment by djibux** [comment]
Same issue here on Debian testing with latest release (1.3.0).

**Comment by Sawiq** [comment]
Confirmed. To reproduce:

* Open an app.
* Choose game, wait for launch.
* Click on [Full screen] button in a popup window
* Press [Esc] key. 

*Expected result*: gfn-electron passes key press to running game
*Current result*: App window exits full screen mode.

Additionally after some gaming:
* Pres [Super] + [F]
* Play the game
* Exit game, wait until closes 
* Press [Super] + [F]

*Expected result*: App window exits full screen mode.
*Current result*: App cannot exit full screen mode.

Verified on Manjaro `Linux 5.10.109-1-MANJARO`

application version:
```
:: Querying AUR...
Repository      : aur
Name            : geforcenow-electron
Keywords        : None
Version         : 1.4.0-1
Description     : Linux desktop client for GeForce NOW, using Electron
URL             : https://github.com/hmlendea/geforcenow-electron
AUR URL         : https://aur.archlinux.org/packages/geforcenow-electron
Groups          : None
Licenses        : GPLv3
Provides        : None
Depends On      : libva
Make Deps       : None
Check Deps      : None
Optional Deps   : None
Conflicts With  : None
Maintainer      : Radeox
Votes           : 7
Popularity      : 0.203020
First Submitted : Tue 29 Dec 2020 10:30:06 PM CET
Last Modified   : Mon 11 Apr 2022 09:39:37 AM CEST
Out-of-date     : No
```

**Comment by AuthFailed** [comment]
Is there any chance that this will be a fix soon?

**Comment by aaronpkelly** [comment]
I just experienced this issue for the first time when I upgraded to the latest release `v1.6.0` after running `sudo flatpak update` (I have no idea what version I was on previously)

So, following [these instructions](https://github.com/flatpak/flatpak/wiki/Tips-&-Tricks#downgrading) , I ran the following command to go back to the v1.5.2 release:
`sudo flatpak update --commit=15af3e79c3b600ec2c991b2e254969d1eaed9c2b1376f7b269ede1dcd21f6942 io.github.hmlendea.geforcenow-electron`

And the issue no longer occurs

I haven't really investigated it more than that, I just want to play my game, but if I have any more info to add I'll add it later

**Comment by UwUnyaa** [comment]
For me, I cannot use the fullscreen shortcut, nor the exit application one, meaning I'm stuck with exiting games by going through the menu inside of them. In my case, I'm on Arch with dwm (X11).

**Comment by UwUnyaa** [comment]
Shortcuts are still broken for me. The only difference is that I need to press ESC once to unlock the pointer and send it to the VM. I might look into this issue, as I'm wondering whether there's a conflict between the renderer process and the main thread shortcuts. GFN tries to do a full screen mode with pointer and keyboard capturing after all.

**Comment by Missidiumnes** [comment]
Idk why, but I still got problem with it, Ubuntu 22.04

**Comment by drusepth** [comment]
This is still an issue for me on Ubuntu 22.04 as well, making many games unplayable. After hitting ESC, the window loses focus and I need to click back into the window in order to track my cursor, register keyboard events, etc.

Running from a console, I can see
```
Game streaming mode state changed to: true
Fullscreen state changed to: true
```
when I launch full-screen mode. I can see those params revert back to false when I exit a game, but interestingly they _don't_ revert back to false when I press escape. Instead, I get the following console error -- which looks unrelated, but I'm including it in case it's not. 
```
[78785:0209/223013.937324:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.PowerManagement.Inhibit.Inhibit: object_path= /org/freedesktop/PowerManagement/Inhibit: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.738" (uid=1000 pid=78785 comm="/snap/geforcenow-electron/17/geforcenow-electron -" label="snap.geforcenow-electron.geforcenow-electron (enforce)") interface="org.freedesktop.PowerManagement.Inhibit" member="Inhibit" error name="(unset)" requested_reply="0" destination="org.freedesktop.PowerManagement" (uid=1000 pid=1965 comm="xfce4-power-manager " label="unconfined")
[78785:0209/223013.937340:ERROR:power_save_blocker_linux.cc(338)] No response to Inhibit() request!
```

Using version 1.10.0 from Ubuntu (snap) package manager.

**Comment by Missidiumnes** [comment]
Is there anything that seems to work according to this? I haven't find the solution till this day and it's still kinda frustrating. Maybe some keylock changes for fullscreen being optional would help?
