### ISSUE TITLE
Can't use xbox controller

### ISSUE THREAD

**Issue by re64trh5hheterrethg** [hmlendea/gfn-electron#67]
Hi,
Thanks for this useful app.
I can't use controller in-game (rocket league).
I'm using a xbox gamepad, that is well recognised in gamepadAPI testing websites.
So I guess flatpack sandboxing is blocking it.
Do you have any idea to get it working?
Thanks!

**Comment by wkitty42** [comment]
looking for same, here... need my controller for several games... kbd+mouse just doesn't work for me... i mean it does but i have other physical problems that get in the way... controller is best way for me and others...

**Comment by hmlendea** [comment]
Is this still an issue?
If so, which version are you using and which installation method?

**Comment by wkitty42** [comment]
yes, it is for me... i just tested it by loading Assassin's Creed: Valhalla in my GFN (free) installation... in the game's settings, the controller input mode is set to mouse&keyboard and is greyed out so it cannot be changed... i find nothing in the GFN settings that tells me if my controller(s) are even found... according to Settings->About i'm using GFN 2.0.34.138/ro...

**Comment by hmlendea** [comment]
Which version of geforcenow-electron _(not GFN itself)_ are you using and which installation method did you use (snap, flatpak, etc)?

**Comment by wkitty42** [comment]
"snap list" shows this: ``` geforcenow              1.1.4                       9      latest/stable  popey               - ```

**Comment by hmlendea** [comment]
That's another snap. Install `geforcenow-electron` (https://snapcraft.io/geforcenow-electron) instead of `geforcenow`. The latest version is 1.1.9.

**Comment by wkitty42** [comment]
ooooohhhhhhh! i didn't realize there were different ones... will i keep my current settings and account log on stuff?

**Comment by hmlendea** [comment]
I don't know

**Comment by wkitty42** [comment]
fair enough :)

**Comment by wkitty42** [comment]
ok, i've installed your geforcenow-electron snap and still have the same... i see no way to determine if my controller is being seen... today i tested with ubisoft Assassins Creed: Valhalla, steam Tomb Raider, and steam No Man's Sky (i have 1000+ hours in it all with controller)... none of them saw the controller... when i play them via my local installations (ubisoft via lutris and the others via steam), they have no problems finding and using the controller...

to be clear, i have an xbox one wireless controller that is connected to my system via usb cable...

is there a command line option which will output loading and diagnostic messages to the console?

could it be that the free GFN accounts simply do not have access to the controller?

**Comment by zanito** [comment]
Same issue for me using the flatpak version of the app 1.1.11 installed via flathub, if I use Chrome web version the controller works fine and is detected by the games I have tried. Using PS3 controller over bluetooth. My guess is probably flatpak related and I tried to adjust the permissions using flatseal but no luck.
Thank for the really excellent work with this app by the way. It works really well apart for the issue with the controller, I would much prefer it to using chrome in my system.

**Comment by wkitty42** [comment]
is it possible that we need to manually enable this snap to access our joystick and controller hardware with ```snap connect geforcenow-electron:joystick```??

i ask because i notice with the ```snap connections geforcenow-electron``` command that joystick, audio-record, and pulseaudio plugs are not connected to any slots...

**Comment by Etaash-mathamsetty** [comment]
im having this issue with the flatpak, I am using a dualsense controller.

**Comment by hmlendea** [comment]
Documentation has just been written [here](https://github.com/hmlendea/gfn-electron/wiki/Troubleshooting#gamepad-controls-are-not-detected) in regards to troubleshooting this problem, in #141 

If the issue still persist even after applying those fixes, feel free to reopen this issue.

**Comment by wkitty42** [comment]
that's the flatpak stuff but what about the snaps? i've already done the `snap connection geforcenow-electron:joystick` thing to no avail...

another maybe important thing is if free GFN accounts can even use their joysticks and controllers or not... i've asked that specific question in several GFN related places (eg: the GFN forums, GFN related snap forums, etc) but it has not been answered by anyone... i know that's not on you but it is quite saddening and frustrating to a point...

**Comment by 1235467** [comment]
controllers work in free GFN account in windows client.idk whether they work in broswer.Mine xbox controller isn't working as well.

**Comment by wkitty42** [comment]
thanks for the info, @1235467 ... it confirms my experience... i've never tried using GFN via a browser... i only use firefox for numerous reasons even though a lot of people say using GFN via the chrome browser works... unfortunately, most all of them are windows users so have no idea what we are dealing with on linux setups...

**Comment by paulatz** [comment]
I confirm that the flatpack works with the workaround from wkitty42, and also that the snap does not work. It could be a problem of the Apparmor profile that does not allow access to the controller (Another bug of the snap which is definitely Apparmor is that the screensaver is not inhibited while playing)

My workarond was to add "deb" to the build targets, build a .deb package and use it instead of this snap nonsense ;-).

cheers
