### ISSUE TITLE
Orange border around fullscreen when clicking while in steam loading state

### ISSUE THREAD

**Issue by ZainlessBrombie** [hmlendea/gfn-electron#68]
An orange border around the fullscreen is shown when I click the screen while being in the steam loading window.
Adding the following code to the preload.js DOMContentLoaded seems to prevent the issue, but might have an impact on accessibility as it applies to _all_ elements in all screens.

```
    const head = document.getElementsByTagName("head")[0];
    const styleTag = document.createElement('style');
    styleTag.innerHTML = ":focus {outline:unset;}";
    head.appendChild(styleTag);
```
The style should only apply to the fullscreen window that is focused and gets the orange border - but it has been quite a day so I did not get around to checking what selector is needed.

**Comment by hmlendea** [comment]
This appears to have been fixed in the newer versions.
Please feel free to reopen if you still experience this bug.
