### ISSUE TITLE
Brightness is low with hardware acceleration

### ISSUE THREAD

**Issue by ilovespicynoodles** [hmlendea/gfn-electron#79]
This is not limited to the app, but i don't know where else to find people working on Linux Geforce NOW issues.
So the issue is that when hardware acceleration is on (which is necessary to play without incredible input lag), the brightness in Geforce NOW is way to low and its hard to play certain games.
This issue does not happen on windows.
![Screenshot from 2021-09-09 20-02-39](https://user-images.githubusercontent.com/36053358/132739378-ad881aeb-420c-4b78-bc1d-65b5c80e2727.png)

![Screenshot from 2021-09-09 20-01-48](https://user-images.githubusercontent.com/36053358/132739386-a299ec73-db78-4d7e-8ed9-139b213b07d9.png)

As you can see, the top one, where hardware acceleration is enabled with the `LIBVA_DRIVER_NAME=iHD` environment variable, is dark and can be incredibly hard to play with.

The bottom picture is without hardware acceleration and has normal brightness, but is unplayable because of input lag.

I remember having this issue in the beginning too and i fixed it, but i don't remember how i did it.
I'm using Nvidia optimus which is a nvidia gpu with a intel integrated graphics that i can switch between.

The same issue happens in a chromium browser if i use the flags in the commandline to launch it with hardware acceleration.
for example: 

```chromium --enable-gpu-rasterization --enable-oop-rasterization --enable-zero-copy --ignore-gpu-blocklist --use-gl=desktop --enable-accelerated-video-decode```

If i take away ```--use-gl=desktop```, then it runs without hardware acceleration and everything is bright but with massive input lag.

I remember it working on KDE and XFCE4 before but i don't remember how? I was able to just install the ```intel-media-driver``` and start up the geforcenow-electron app and it would work perfectly with normal brightness. but now its all dark.

Here are my graphics processors and other system info:
```
*-display                 
       description: 3D controller
       product: GP107M [GeForce GTX 1050 Mobile]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:146 memory:a3000000-a3ffffff memory:90000000-9fffffff memory:a0000000-a1ffffff ioport:4000(size=128)
  *-display
       description: VGA compatible controller
       product: CoffeeLake-H GT2 [UHD Graphics 630]
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list
       configuration: driver=i915 latency=0
       resources: irq:143 memory:a2000000-a2ffffff memory:b0000000-bfffffff ioport:5000(size=64) memory:c0000-dffff
```

![image](https://user-images.githubusercontent.com/36053358/132740500-519bf92c-19cd-4a0b-8183-997cdaf03a38.png)

**Comment by sgtnasty** [comment]
I had a **similar** issue with GFN, I turned off HDR on my monitor and all the brightness was fixed in my GFN games.

**Comment by ilovespicynoodles** [comment]
> I had a **similar** issue with GFN, I turned off HDR on my monitor and all the brightness was fixed in my GFN games.

I sadly don't have HDR on my laptop screen :(

**Comment by hmlendea** [comment]
Does this issue still apply on the latest version?
