### ISSUE TITLE
My microphone is not working

### ISSUE THREAD

**Issue by marcleonschulz** [hmlendea/gfn-electron#86]

**Comment by kelvie** [comment]
Mine also didn't work in the snap version, I used the flatpak version and it seems to be OK.

**Comment by hmlendea** [comment]
Should be fixed in 1.1.9, let me know if the issue persists.

**Comment by Tealk** [comment]
I use AUR Version and mic does not work

**Comment by hmlendea** [comment]
Is this still an issue for the latest version?
Seems to have been working well for a while now, at least for the AUR and flatpak versions.
